build:
    docker:
      - image: circleci/node:latest
    working_directory: ~/felinefolia-react
    steps:
      - attach_workspace:
          at: ~/felinefolia-react
      - run: yarn install
      - run:
          name: yarn build
          command: |
            if [ "${CIRCLE_BRANCH}" == "production" ]; then
              CI=true PUBLIC_URL=https://felinefolia.com yarn build
            elif [ "${CIRCLE_BRANCH}" == "development" ]; then
              CI=true PUBLIC_URL=https://felinefolia.com yarn build
            elif [ "${CIRCLE_BRANCH}" == "master" ]; then
              CI=true PUBLIC_URL=https://felinefolia.com yarn build
            else
              echo "This failed miserably!"
            fi
      - persist_to_workspace:
          root: .
          paths: .